language: java

jdk:
  - oraclejdk8

env:
  global:
    - DFB_PROJECT_DIR=$(pwd)
    - TMP_PROJECT_PARENT_DIR=$(dirname $DFB_PROJECT_DIR) # Temp var to avoid strange error with "))" at build  server in DFB_OWNER_NAME
    - DFB_BUILD_ID=$TRAVIS_BUILD_ID
    - DFB_PRODUCT_NAME=$(basename $DFB_PROJECT_DIR)
    - DFB_OWNER_NAME=$(basename $TMP_PROJECT_PARENT_DIR)
    # This name is important convention, same is used in TravisWebhookController
    - DFB_PRODUCT_KEY="${DFB_OWNER_NAME}_${DFB_PRODUCT_NAME}"
    - AWS_BUCKET="aline-external-ci-artifacts"
    - DFB_AGENTS_URL=https://s3.amazonaws.com/${AWS_BUCKET}/agents
    - DFB_PACKAGING_URL=s3://${AWS_BUCKET}/artifacts/travis/
    - DFB_AWS_OUTPUT_PATH=/artifacts/travis/${DFB_PRODUCT_KEY}/${DFB_BUILD_ID}/output/
    - AWS_ACCESS_KEY_ID=AKIAIIU2LBOCCKXAIFZQ
    - AWS_SECRET_ACCESS_KEY=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
    - JTO=-javaagent:dfbuild-agent.jar=PACKAGING_BASE_URI=$DFB_PACKAGING_URL,PRODUCT_KEY=$DFB_PRODUCT_KEY/,BUILD_KEY=$DFB_BUILD_ID/,MODULES_KEY=modules/,START_TIME=0,BUILD_BASE_DIR=$DFB_PROJECT_DIR

before_install:
  - wget $DFB_AGENTS_URL/beforebuild.sh
  - chmod a+x beforebuild.sh
  - ./beforebuild.sh
script:
  - export JAVA_TOOL_OPTIONS=$JTO # Set it just before build. Travis calls java for version purposes BEFORE before_install and fails
  - mvn clean test-compile

after_success:
  - unset JAVA_TOOL_OPTIONS # unset because jacoco agent conflicts with dfagent
  - env > env.file
  - mvn test

addons:
  artifacts:
    debug: true
    paths:
      - $DFB_PROJECT_DIR/env.file
      - $(git ls-files -oi -x *.exec | tr "\n" ":")
    target_paths: $DFB_AWS_OUTPUT_PATH
    bucket: $AWS_BUCKET

notifications:
 webhooks:
  urls:
    - "http://df-sdk-feed-dev.us-east-1.elasticbeanstalk.com/webhooks/travis"
  on_success: always
  on_failure: never
  on_start: never